version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: quannex-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-admin-api
    networks:
      - observability
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: quannex-grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - observability
    restart: unless-stopped

  # Opcional: Alertmanager para notificaciones
  alertmanager:
    image: prom/alertmanager:latest
    container_name: quannex-alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=http://localhost:9093
    networks:
      - observability
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  observability:
    driver: bridge
