name: CI Quality Gate

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build-test-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Security Audit
        run: npm audit --omit=dev --audit-level=high
        timeout-minutes: 2

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format

      - name: Unit + Coverage
        run: npm run test:cov

      - name: Quality Gate
        run: npm run quality:gate

      - name: Policy Gate
        run: node scripts/policy-check.mjs

      - name: Start Metrics Server
        run: |
          npm run dev &
          sleep 5
        background: true

      - name: Metrics Sanity Check
        run: |
          curl -sf http://localhost:3000/metrics | grep -q "qn_http_requests_total" || (echo "No metrics exported" && exit 1)
          curl -sf http://localhost:3000/metrics | grep -q "qn_agent_executions_total" || (echo "Agent metrics missing" && exit 1)
          echo "✅ Metrics exported correctly"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Run legacy security tests
        run: npm run security:deps:moderate
        continue-on-error: true

  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
      - run: npm run quannex:check reports/QUANNEX-METRICAS-USO-IMPLEMENTACION.md
      - run: test -f reports/QUANNEX-METRICAS-USO-IMPLEMENTACION.md && echo "📊 Metrics report present"

  taskdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build

      - name: TaskDB budget check
        run: node scripts/taskdb-budget.mjs
        continue-on-error: true

      - name: TaskDB smoke test
        run: npm run smoke:taskdb

      - name: Policy versioning acceptance
        run: npm run taskdb:policy:acceptance
