name: security-and-pathing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type-check
        run: npx tsc -p tsconfig.json --noEmit

      - name: Lint imports
        run: |
          npx eslint . --ext .ts,.tsx,.js,.mjs || true

      - name: Security deps
        run: |
          bash core/scripts/security-deps-simple.sh -v || true

      - name: Security audit
        run: |
          bash core/scripts/security-audit.sh || true

      - name: Upload security artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts-${{ github.sha }}
          if-no-files-found: ignore
          path: |
            security-reports/**
            .reports/security/**
            audit.json
            /tmp/npm-audit.json
