name: Security Audit (PR-fast)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Security Audit (PR-fast)
        run: npm audit --omit=dev --audit-level=high

      - name: Security Audit Results
        if: failure()
        run: |
          echo "❌ Security audit failed - HIGH/CRITICAL vulnerabilities found"
          echo "Run 'npm audit' locally to see details"
          exit 1
